# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'FlicksMovie' do
    pod 'AFNetworking', '~> 2.6.0'
    pod 'MBProgressHUD', '~> 1.0.0'
end
